WIP: Remove WDN style references
unl/UNL_ENews pull request #100
Opened 2021-12-20 19:16 UTC by jsturek

2021-12-20 19:22 UTC, jsturek commented on www/js/socialmediashare.js
> +    shareButtonTemplate: '<button class="wdn-dropdown-widget-button" aria-pressed="false" aria-haspopup="true" aria-controls="wdn_share_{{id}}"><span class="wdn-icon-share" aria-hidden="true"></span>
This file has several wdn class references (mostly wdn-icon-*).  I was unable to verify that this file is actually needed.  If not we should just remove it.  It appears to only be used by `submission.js` for `createGoURL` functionality.

2022-01-18 21:40 UTC, skoolbus39 requested changes

2022-01-18 21:40 UTC, skoolbus39 commented on www/templates/html/ENews/Manager.tpl.php
> +</script>
No newline at end of file

2022-01-27 14:49 UTC, ericras approved these changes

2022-01-27 18:23 UTC, merged